/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
// Runtime types generated with workerd@1.20260518.0 2026-05-09 nodejs_compat
declare namespace Cloudflare {
	interface Env {
		MEDIA: R2Bucket;
		DB: D1Database;
		LOADER: WorkerLoader;
	}
}
interface Env extends Cloudflare.Env {}
