export const AWCMS_SIKESRA_PERMISSIONS = {
	dashboardRead: "awcms:sikesra:dashboard:read",
	settingsRead: "awcms:sikesra:settings:read",
	settingsUpdate: "awcms:sikesra:settings:update",
	auditRead: "awcms:sikesra:audit:read",
	publicStatusRead: "awcms:sikesra:public-status:read",
	stateTouch: "awcms:sikesra:state:touch",
	permissionCatalogRead: "awcms:sikesra:permissions:read",
	permissionCatalogWrite: "awcms:sikesra:permissions:write",
	roleCatalogRead: "awcms:sikesra:roles:read",
	roleCatalogWrite: "awcms:sikesra:roles:write",
	accessPreviewRead: "awcms:sikesra:access-preview:read",
	abacAttributeRead: "awcms:sikesra:abac-attributes:read",
	abacAttributeWrite: "awcms:sikesra:abac-attributes:write",
	abacPolicyRead: "awcms:sikesra:abac-policies:read",
	abacPolicyWrite: "awcms:sikesra:abac-policies:write",
	abacPreviewRead: "awcms:sikesra:abac-preview:read",
	sikesraDashboardRead: "sikesra.dashboard.read",
	sikesraRegistryRead: "sikesra.registry.read",
	sikesraRegistryCreate: "sikesra.registry.create",
	sikesraRegistryUpdate: "sikesra.registry.update",
	sikesraRegistryDeleteSoft: "sikesra.registry.delete_soft",
	sikesraRegistryReadSensitive: "sikesra.registry.read_sensitive",
	sikesraDocumentRead: "sikesra.document.read",
	sikesraDocumentUpload: "sikesra.document.upload",
	sikesraDocumentReadRestricted: "sikesra.document.read_restricted",
	sikesraImportCreate: "sikesra.import.create",
	sikesraImportValidate: "sikesra.import.validate",
	sikesraImportPromote: "sikesra.import.promote",
	sikesraVerificationRead: "sikesra.verification.read",
	sikesraVerificationApprove: "sikesra.verification.approve",
	sikesraVerificationReject: "sikesra.verification.reject",
	sikesraReportRead: "sikesra.report.read",
	sikesraExportCreate: "sikesra.export.create",
	sikesraExportRestricted: "sikesra.export.restricted",
	sikesraAuditRead: "sikesra.audit.read",
	sikesraSettingsRead: "sikesra.settings.read",
	sikesraSettingsUpdate: "sikesra.settings.update",
	sikesraRbacManage: "sikesra.rbac.manage",
	sikesraAbacManage: "sikesra.abac.manage",
} as const;

export const AWCMS_SIKESRA_PERMISSION_LIST = Object.values(AWCMS_SIKESRA_PERMISSIONS);
