export function getExampleAdminCopy(locale: string | undefined) {
	if (locale?.startsWith("id")) {
		return {
			navTitle: "Pusat Operasi Plugin",
			navDescription: "Navigasi referensi untuk alur registry, verifikasi, laporan, akses, dan ABAC.",
			never: "Tidak pernah",
			somethingWentWrong: "Terjadi kesalahan",
			retry: "Coba lagi",
			refresh: "Segarkan",
			loadingGovernanceStatus: "Memuat status tata kelola...",
			loadingAccessHealth: "Memuat kesehatan akses...",
			loadingAbacStatus: "Memuat status ABAC...",
			loadingPluginOverview: "Memuat ringkasan plugin...",
			noStatusYet: "Belum ada status",
			noStatusYetDescription: "Plugin belum mengembalikan data ringkasan.",
			noHealthData: "Belum ada data kesehatan",
			noHealthDataDescription: "Katalog akses belum mengembalikan data kesehatan.",
			noAbacData: "Belum ada data ABAC",
			noAbacDataDescription: "Route ABAC belum mengembalikan data kesehatan.",
			noOverviewData: "Belum ada data ringkasan",
			noOverviewDataDescription: "Plugin belum mengembalikan data ringkasan.",
			audit: "Audit",
			lifecycle: "Siklus hidup",
			publicHits: "Hit publik",
			mode: "Mode",
			lastLifecycle: "Siklus hidup terakhir",
			permissions: "Izin",
			roles: "Peran",
			matrices: "Matriks",
			users: "Pengguna",
			reviewNeeded: "Perlu ditinjau",
			healthy: "Sehat",
			catalogGapSummary: (rolesWithoutPermissions: number, usersWithoutRoles: number) => `${rolesWithoutPermissions} peran tanpa izin dan ${usersWithoutRoles} penugasan pengguna tanpa peran.`,
			catalogGapNone: "Tidak ada gap kesehatan katalog yang terlihat.",
			attributes: "Atribut",
			policies: "Kebijakan",
			subjects: "Subjek",
			resources: "Sumber daya",
			explicitDenyPolicies: (count: number) => `Kebijakan deny eksplisit: ${count}`,
			overviewEyebrow: "Plugin AWCMS-Micro",
			overviewTitle: "Pusat Operasi Plugin",
			overviewDescription: "Selamat datang di plugin demonstrasi AWCMS-Micro. Konsol ini memungkinkan Anda mengelola log audit, event lifecycle, dan simulasi kebijakan Role-Based dan Attribute-Based Access Control (RBAC/ABAC) secara aman tanpa mengubah core EmDash.",
			refreshDashboard: "Segarkan dasbor",
			overviewSuccess: "Dasbor berhasil diinisialisasi. Semua sub-sistem plugin (Audit, RBAC, ABAC) aktif penuh dan terhubung ke database dasar.",
			auditEventsStored: "Event audit tersimpan",
			auditEventsStoredHint: "Melacak semua aktivitas plugin yang kritis",
			lifecycleTriggers: "Pemicu lifecycle",
			lastRecorded: (value: string) => `Terakhir tercatat: ${value}`,
			publicApiHits: "Hit API publik",
			lastCron: (value: string) => `Cron terakhir: ${value}`,
			openModule: "Buka modul",
			pluginConfiguration: "Konfigurasi plugin",
			pluginConfigurationDescription: "Kelola pengaturan global untuk plugin ini. Pengaturan ini menentukan perilaku route status publik dan alur kerja tata kelola.",
			publicStatusLabel: "Label status publik",
			publicStatusLabelHint: "Ditampilkan oleh route status aman-publik.",
			auditRetentionDays: "Hari retensi audit",
			auditRetentionDaysHint: "Gunakan angka positif. Contoh: 30.",
			governanceMode: "Mode tata kelola",
			governanceModeHint: "Hanya observasi log, review, atau jalankan jalur enforcement demo.",
			observe: "Observasi",
			review: "Tinjau",
			enforceDemo: "Terapkan demo",
			metadataCanonicalBase: "Basis canonical metadata",
			metadataCanonicalBaseHint: "URL dasar opsional untuk contoh metadata halaman.",
			saving: "Menyimpan...",
			saveSettings: "Simpan pengaturan",
			modeLabel: (value: string) => `Mode: ${value}`,
			currentStatus: "Status saat ini",
			statusLabel: "Label status",
			notSet: "Belum diatur",
			retention: "Retensi",
			retentionDays: (value: number) => `${value} hari`,
			governance: "Tata kelola",
			canonicalBase: "Basis canonical",
			recentAuditEvents: "Event audit terbaru",
			recentAuditEventsDescription: "Aktivitas plugin terbaru, berguna untuk verifikasi cepat setelah mengubah pengaturan.",
			noRecentEvents: "Belum ada event terbaru",
			noRecentEventsDescription: "Picu aksi plugin untuk mengisi aliran audit.",
		settingsSavedSuccessfully: "Pengaturan berhasil disimpan.",
		failedToSaveSettings: "Gagal menyimpan pengaturan",
		registrySteps: ["Identitas", "Wilayah", "Dokumen", "Tinjauan"],
		registryEyebrow: "Registry",
		registryTitle: "Intake dan verifikasi registry",
		registryDescription: "UI referensi untuk onboarding entitas registry, melacak cakupan wilayah, dan menunjukkan bagaimana pengenal sensitif tetap dimasking sampai tahap review.",
		registryEntities: "Entitas registry",
		registryEntitiesHint: "Record referensi dalam antrean sampel",
		verifiedRecords: "Record terverifikasi",
		verifiedRecordsHint: "Record yang mencapai verifikasi aktif",
		restrictedEntries: "Entri terbatas",
		restrictedEntriesHint: "Baris yang memerlukan masking di tampilan operator",
		registryQueue: "Antrean registry",
		registryQueueDescription: "Record referensi SIKESRA yang deterministik dengan tahap, sensitivitas, dan cakupan wilayah.",
		progressiveInputWizard: "Wizard input progresif",
		progressiveInputWizardDescription: "Alur operator ringkas yang menahapkan entri data dan hanya menampilkan kode referensi pada tahap tinjauan akhir.",
		stepLabel: (step: number, label: string) => `Langkah ${step}: ${label}`,
		registryStepIdentity: "Mulai dengan detail identitas dan label yang mudah dibaca manusia.",
		registryStepRegion: "Tambahkan field cakupan wilayah agar reviewer bisa memeriksa batas yurisdiksi.",
		registryStepDocuments: "Lampirkan dokumen dan simpan metadata sensitif di luar tampilan publik.",
		registryStepReview: "Tinjau kode referensi yang dimasking dan verifikasi tahap akhir sebelum aktivasi.",
		registryLabel: "Label registry",
		registryLabelHint: "Nama entri referensi yang ditampilkan ke operator.",
		provinceCode: "Kode provinsi",
		provinceCodeHint: "Kode wilayah administratif.",
		sensitivity: "Sensitivitas",
		sensitivityHint: "Mengontrol masking dan eksposur publik.",
		preview: "Pratinjau",
		code: "Kode",
		label: "Label",
		region: "Wilayah",
		untitledRegistryEntity: "Entitas registry tanpa judul",
		previous: "Sebelumnya",
		next: "Berikutnya",
		activeReferenceRecord: "Record referensi aktif",
		verificationEyebrow: "Verifikasi",
		verificationTitle: "Antrean verifikasi",
		verificationDescription: "Tampilan antrean ringkas untuk approval bertahap, review tertunda, dan eskalasi lintas langkah desa, kecamatan, dan kabupaten.",
		loadingVerificationQueue: "Memuat antrean verifikasi...",
		advancing: "Memajukan...",
		advanceTo: (code: string, nextStage: string | null) => `Majukan ${code} ke ${nextStage}`,
		advancedTo: (code: string, stage: string) => `${code} dimajukan ke ${stage}.`,
		queuedEvents: "Event antrean",
		queuedEventsHint: "Riwayat referensi deterministik",
		approved: "Disetujui",
		approvedHint: "Checkpoint verifikasi yang diterima",
		needsReview: "Perlu review",
		needsReviewHint: "Item yang masih butuh tindak lanjut",
		registryVerificationQueue: "Antrean verifikasi registry",
		registryVerificationQueueDescription: "Status verifikasi live yang bisa dimajukan satu tahap sekali dari UI referensi.",
		final: "final",
		documentsCount: "Dokumen",
		idLabel: "ID",
		referenceVerificationEvents: "Event verifikasi referensi",
		referenceVerificationEventsDescription: "Progres tahap dari draft ke verifikasi aktif.",
		actor: "Aktor",
		created: "Dibuat",
		documentsEyebrow: "Dokumen",
		documentsTitle: "Dokumen pendukung",
		documentsDescription: "Metadata dokumen untuk model referensi registry, termasuk klasifikasi sensitivitas dan sumber verifikasi.",
		documentsMetric: "Dokumen",
		documentsMetricHint: "Metadata dokumen referensi",
		sensitiveDocs: "Dokumen sensitif",
		sensitiveDocsHint: "Record yang harus tetap dimasking",
		verifiedSources: "Sumber terverifikasi",
		verifiedSourcesHint: "Pengidentifikasi verifier yang unik",
		documentCatalog: "Katalog dokumen",
		documentCatalogDescription: "Pengenal entitas tertaut dimasking kecuali dokumen secara eksplisit aman-publik.",
		entity: "Entitas",
		issued: "Diterbitkan",
		verifiedBy: "Diverifikasi oleh",
		reportsEyebrow: "Laporan",
		reportsTitle: "Agregat publik",
		reportsDescription: "Surface pelaporan aman-publik yang hanya menampilkan hitungan kasar dan menghindari pengenal privat atau detail record sensitif.",
		categories: "Kategori",
		categoriesHint: "Bucket ringkasan aman-publik",
		suppressed: "Disupresi",
		suppressedHint: "Bucket yang disembunyikan dari detail publik",
		visible: "Terlihat",
		visibleHint: "Bucket yang aman ditampilkan terbuka",
		aggregateCategories: "Kategori agregat",
		aggregateCategoriesDescription: "Jumlah hanya ditampilkan ketika kategori tidak disupresi.",
		category: "Kategori",
		total: "Total",
		verified: "Terverifikasi",
		status: "Status",
		masked: "dimasking",
		publicNote: "Catatan publik",
		publicNoteDescription: "Catatan ini menjelaskan mengapa agregat aman untuk ditampilkan secara publik.",
		displayRule: "Aturan tampil",
		displayRuleDescription: "Bucket yang dimasking tetap diringkas tetapi tidak mengungkap detail tingkat entitas, sesuai pola agregat aman-publik.",
		auditEyebrow: "Audit",
		auditTitle: "Riwayat event",
		auditDescription: "Aliran berbasis storage yang menampilkan perilaku plugin, aktor, scope, dan timestamp.",
		loadingAuditLog: "Memuat log audit...",
		noAuditEvents: "Belum ada event audit",
		noAuditEventsDescription: "Aksi plugin akan muncul di sini setelah hook atau route dijalankan.",
		summary: "Ringkasan",
		scopeActor: "Scope / aktor",
		time: "Waktu",
		loadingPermissions: "Memuat izin...",
		accessEyebrow: "Akses",
		permissionCatalog: "Katalog izin",
		permissionCatalogDescription: "Buat izin milik plugin dengan slug, label, scope, dan deskripsi yang eksplisit.",
		addPermission: "Tambah izin",
		addPermissionDescription: "Gunakan slug stabil bertitik seperti content.read.public.",
		slug: "Slug",
		scope: "Cakupan",
		descriptionLabel: "Deskripsi",
		savePermission: "Simpan izin",
		permissionSaved: "Izin disimpan.",
		failedToSavePermission: "Gagal menyimpan izin",
		existingPermissions: "Izin yang ada",
		existingPermissionsDescription: (count: number) => `${count} izin dalam katalog plugin.`,
		noPermissionsYet: "Belum ada izin",
		noPermissionsYetDescription: "Buat izin untuk mulai membangun matriks peran.",
		noDescriptionProvided: "Belum ada deskripsi.",
			dashboardCards: [
				{ title: "Rumah Ibadah", description: "Daftarkan data rumah ibadah dan jaga visibilitas cakupan wilayah untuk operator.", status: "Siap", badge: "Inti" },
				{ title: "Lembaga Keagamaan", description: "Lacak data kelembagaan dan progres verifikasinya.", status: "Siap", badge: "Inti" },
				{ title: "Pendidikan Keagamaan", description: "Jaga entri pendidikan tetap bertahap untuk verifikasi dan pelaporan.", status: "Tinjau", badge: "Antrean" },
				{ title: "Lembaga Kesejahteraan Sosial", description: "Tinjau data terkait kesejahteraan dengan mempertimbangkan agregasi aman-publik.", status: "Siap", badge: "Laporan" },
				{ title: "Guru Agama", description: "Jaga metadata staf tetap selaras dengan alur akses dan verifikasi.", status: "Siap", badge: "Akses" },
				{ title: "Yatim Piatu", description: "Referensi data dukungan anak dengan masking yang hati-hati dan jejak audit.", status: "Audit", badge: "Audit" },
				{ title: "Disabilitas", description: "Kelola data sensitif dengan surface preview yang siap ABAC.", status: "Terbatas", badge: "ABAC" },
				{ title: "Lansia Terlantar", description: "Jaga contoh sensitivitas tinggi tetap tersedia tanpa mengekspos identitas publik.", status: "Terkunci", badge: "Dokumen" },
			],
		};
	}

	return {
		navTitle: "Plugin Operations Center",
		navDescription: "Reference navigation for registry, verification, reports, access, and ABAC flows.",
		never: "Never",
		somethingWentWrong: "Something went wrong",
		retry: "Retry",
		refresh: "Refresh",
		loadingGovernanceStatus: "Loading governance status...",
		loadingAccessHealth: "Loading access health...",
		loadingAbacStatus: "Loading ABAC status...",
		loadingPluginOverview: "Loading plugin overview...",
		noStatusYet: "No status yet",
		noStatusYetDescription: "The plugin did not return summary data.",
		noHealthData: "No health data",
		noHealthDataDescription: "The access catalog did not return health data.",
		noAbacData: "No ABAC data",
		noAbacDataDescription: "The ABAC routes did not return health data.",
		noOverviewData: "No overview data",
		noOverviewDataDescription: "The plugin did not return overview data.",
		audit: "Audit",
		lifecycle: "Lifecycle",
		publicHits: "Public hits",
		mode: "Mode",
		lastLifecycle: "Last lifecycle",
		permissions: "Permissions",
		roles: "Roles",
		matrices: "Matrices",
		users: "Users",
		reviewNeeded: "Review needed",
		healthy: "Healthy",
		catalogGapSummary: (rolesWithoutPermissions: number, usersWithoutRoles: number) => `${rolesWithoutPermissions} role(s) without permissions and ${usersWithoutRoles} user assignment(s) without roles.`,
		catalogGapNone: "No obvious catalog health gaps detected.",
		attributes: "Attributes",
		policies: "Policies",
		subjects: "Subjects",
		resources: "Resources",
		explicitDenyPolicies: (count: number) => `Explicit deny policies: ${count}`,
		overviewEyebrow: "AWCMS-Micro plugin",
		overviewTitle: "Plugin Operations Center",
		overviewDescription: "Welcome to the AWCMS-Micro demonstration plugin. This console allows you to manage audit logs, lifecycle events, and simulate Role-Based and Attribute-Based Access Control (RBAC/ABAC) policies securely without modifying the EmDash core.",
		refreshDashboard: "Refresh Dashboard",
		overviewSuccess: "Dashboard initialized successfully. All plugin sub-systems (Audit, RBAC, ABAC) are fully active and connected to the underlying D1 database.",
		auditEventsStored: "Audit Events Stored",
		auditEventsStoredHint: "Tracks all critical plugin activity",
		lifecycleTriggers: "Lifecycle Triggers",
		lastRecorded: (value: string) => `Last recorded: ${value}`,
		publicApiHits: "Public API Hits",
		lastCron: (value: string) => `Last chron: ${value}`,
		openModule: "Open module",
		pluginConfiguration: "Plugin Configuration",
		pluginConfigurationDescription: "Manage global settings for this plugin. These settings dictate how the public status route and governance workflows behave.",
		publicStatusLabel: "Public status label",
		publicStatusLabelHint: "Shown by the public-safe status route.",
		auditRetentionDays: "Audit retention days",
		auditRetentionDaysHint: "Use a positive number. Example: 30.",
		governanceMode: "Governance mode",
		governanceModeHint: "Observe logs only, review, or run the demo enforcement path.",
		observe: "Observe",
		review: "Review",
		enforceDemo: "Enforce demo",
		metadataCanonicalBase: "Metadata canonical base",
		metadataCanonicalBaseHint: "Optional base URL for page metadata examples.",
		saving: "Saving...",
		saveSettings: "Save settings",
		modeLabel: (value: string) => `Mode: ${value}`,
		currentStatus: "Current status",
		statusLabel: "Status label",
		notSet: "Not set",
		retention: "Retention",
		retentionDays: (value: number) => `${value} day(s)`,
		governance: "Governance",
		canonicalBase: "Canonical base",
		recentAuditEvents: "Recent audit events",
		recentAuditEventsDescription: "Latest plugin activity, useful for quick verification after changing settings.",
		noRecentEvents: "No recent events",
		noRecentEventsDescription: "Trigger plugin actions to populate the audit stream.",
		settingsSavedSuccessfully: "Settings saved successfully.",
		failedToSaveSettings: "Failed to save settings",
		registrySteps: ["Identity", "Region", "Documents", "Review"],
		registryEyebrow: "Registry",
		registryTitle: "Registry intake and verification",
		registryDescription: "Reference UI for onboarding registry entities, tracking their region scope, and showing how sensitive identifiers stay masked until the review step.",
		registryEntities: "Registry entities",
		registryEntitiesHint: "Reference records in the sample queue",
		verifiedRecords: "Verified records",
		verifiedRecordsHint: "Records that reached active verification",
		restrictedEntries: "Restricted entries",
		restrictedEntriesHint: "Rows that require masking in operator views",
		registryQueue: "Registry queue",
		registryQueueDescription: "Deterministic SIKESRA reference records with stage, sensitivity, and region scope.",
		progressiveInputWizard: "Progressive input wizard",
		progressiveInputWizardDescription: "A compact operator flow that stages the data entry and only reveals the reference code at the final review step.",
		stepLabel: (step: number, label: string) => `Step ${step}: ${label}`,
		registryStepIdentity: "Start with identity details and a human-readable label.",
		registryStepRegion: "Add region scope fields so reviewers can check jurisdiction boundaries.",
		registryStepDocuments: "Attach documents and keep the sensitive metadata out of the public view.",
		registryStepReview: "Review the masked reference code and verify the final stage before activation.",
		registryLabel: "Registry label",
		registryLabelHint: "Reference entry name shown to operators.",
		provinceCode: "Province code",
		provinceCodeHint: "Administrative region code.",
		sensitivity: "Sensitivity",
		sensitivityHint: "Controls masking and public exposure.",
		preview: "Preview",
		code: "Code",
		label: "Label",
		region: "Region",
		untitledRegistryEntity: "Untitled registry entity",
		previous: "Previous",
		next: "Next",
		activeReferenceRecord: "Active reference record",
		verificationEyebrow: "Verification",
		verificationTitle: "Verification queue",
		verificationDescription: "A compact queue view for staged approvals, pending review, and escalation across village, district, and regency steps.",
		loadingVerificationQueue: "Loading verification queue...",
		advancing: "Advancing...",
		advanceTo: (code: string, nextStage: string | null) => `Advance ${code} to ${nextStage}`,
		advancedTo: (code: string, stage: string) => `Advanced ${code} to ${stage}.`,
		queuedEvents: "Queued events",
		queuedEventsHint: "Deterministic reference history",
		approved: "Approved",
		approvedHint: "Accepted verification checkpoints",
		needsReview: "Needs review",
		needsReviewHint: "Items that still need follow-up",
		registryVerificationQueue: "Registry verification queue",
		registryVerificationQueueDescription: "Live verification state that can be advanced one stage at a time from the reference UI.",
		final: "final",
		documentsCount: "Documents",
		idLabel: "ID",
		referenceVerificationEvents: "Reference verification events",
		referenceVerificationEventsDescription: "Stage progression from draft to active verification.",
		actor: "Actor",
		created: "Created",
		documentsEyebrow: "Documents",
		documentsTitle: "Supporting documents",
		documentsDescription: "Document metadata for the registry reference model, including sensitivity classification and verification source.",
		documentsMetric: "Documents",
		documentsMetricHint: "Reference document metadata",
		sensitiveDocs: "Sensitive docs",
		sensitiveDocsHint: "Records that should remain masked",
		verifiedSources: "Verified sources",
		verifiedSourcesHint: "Unique verifier identifiers",
		documentCatalog: "Document catalog",
		documentCatalogDescription: "The linked entity identifier is masked unless the document is explicitly public-safe.",
		entity: "Entity",
		issued: "Issued",
		verifiedBy: "Verified by",
		reportsEyebrow: "Reports",
		reportsTitle: "Public aggregate",
		reportsDescription: "A public-safe reporting surface that exposes only coarse counts and avoids private identifiers or sensitive record details.",
		categories: "Categories",
		categoriesHint: "Public-safe summary buckets",
		suppressed: "Suppressed",
		suppressedHint: "Buckets hidden from public detail",
		visible: "Visible",
		visibleHint: "Buckets safe to display openly",
		aggregateCategories: "Aggregate categories",
		aggregateCategoriesDescription: "Counts are shown only when the category is not suppressed.",
		category: "Category",
		total: "Total",
		verified: "Verified",
		status: "Status",
		masked: "masked",
		publicNote: "Public note",
		publicNoteDescription: "The caveat explains why the aggregate is safe for public display.",
		displayRule: "Display rule",
		displayRuleDescription: "Masked buckets remain summarized but do not reveal entity-level details, matching the public-safe aggregate pattern.",
		auditEyebrow: "Audit",
		auditTitle: "Event history",
		auditDescription: "Storage-backed stream showing plugin behavior, actors, scopes, and timestamps.",
		loadingAuditLog: "Loading audit log...",
		noAuditEvents: "No audit events",
		noAuditEventsDescription: "Plugin actions will appear here after hooks or routes run.",
		summary: "Summary",
		scopeActor: "Scope / actor",
		time: "Time",
		loadingPermissions: "Loading permissions...",
		accessEyebrow: "Access",
		permissionCatalog: "Permission catalog",
		permissionCatalogDescription: "Create plugin-owned permissions with explicit slugs, labels, scopes, and descriptions.",
		addPermission: "Add permission",
		addPermissionDescription: "Use stable dot-separated slugs such as content.read.public.",
		slug: "Slug",
		scope: "Scope",
		descriptionLabel: "Description",
		savePermission: "Save permission",
		permissionSaved: "Permission saved.",
		failedToSavePermission: "Failed to save permission",
		existingPermissions: "Existing permissions",
		existingPermissionsDescription: (count: number) => `${count} permission(s) in the plugin catalog.`,
		noPermissionsYet: "No permissions yet",
		noPermissionsYetDescription: "Create a permission to begin building the role matrix.",
		noDescriptionProvided: "No description provided.",
		dashboardCards: [
			{ title: "Worship Places", description: "Register worship place records and keep region scope visible for operators.", status: "Ready", badge: "Core" },
			{ title: "Religious Institutions", description: "Track institutional records and their verification progress.", status: "Ready", badge: "Core" },
			{ title: "Religious Education", description: "Keep education entries staged for verification and reporting.", status: "Review", badge: "Queue" },
			{ title: "Social Welfare Institutions", description: "Review welfare-related records with public-safe aggregation in mind.", status: "Ready", badge: "Report" },
			{ title: "Religion Teachers", description: "Keep staff metadata aligned with the access and verification workflow.", status: "Ready", badge: "Access" },
			{ title: "Orphans", description: "Reference child-support records with careful masking and audit traces.", status: "Audit", badge: "Audit" },
			{ title: "Disabilities", description: "Manage sensitive records with ABAC-ready preview surfaces.", status: "Restricted", badge: "ABAC" },
			{ title: "Abandoned Elderly", description: "Keep high-sensitivity examples available without exposing public identifiers.", status: "Locked", badge: "Docs" },
		],
	};
}
